{
 "title": "QuizHub Microservices Overview",
 "tags": [
  "quizhub",
  "microservices"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "JVM Heap Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "HTTP Requests Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{application}} - {{uri}}"
    }
   ]
  },
  {
   "title": "Active JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "GC Pause Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "jvm_gc_pause_seconds_count", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Hikari Active Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "hikaricp_connections_active", "legendFormat": "{{application}} - {{pool}}" }
   ]
  },
  {
   "title": "Kafka Producer Record Send Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kafka_producer_record_send_total",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Redis Cache Gets Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "cache_gets_total", "legendFormat": "{{application}} - {{name}}" }
   ]
  }
 ]
}