spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: http://${AUTH_SERVICE_HOST:localhost}:${AUTH_SERVICE_PORT:9001}
              predicates:
                - Path=/api/v1/auth/**
            - id: quiz-service
              uri: http://${QUIZ_SERVICE_HOST:localhost}:${QUIZ_SERVICE_PORT:9002}
              predicates:
                - Path=/api/v1/quizzes/**
            - id: question-service
              uri: http://${QUESTION_SERVICE_HOST:localhost}:${QUESTION_SERVICE_PORT:9003}
              predicates:
                - Path=/api/v1/questions/**
            - id: submission-service
              uri: http://${SUBMISSION_SERVICE_HOST:localhost}:${SUBMISSION_SERVICE_PORT:9004}
              predicates:
                - Path=/api/v1/submissions/**
            - id: result-service
              uri: http://${RESULT_SERVICE_HOST:localhost}:${RESULT_SERVICE_PORT:9005}
              predicates:
                - Path=/api/v1/results/**
            - id: ai-agent-service
              uri: http://${AI_AGENT_SERVICE_HOST:localhost}:${AI_AGENT_SERVICE_PORT:9006}
              predicates:
                - Path=/api/v1/ai/**


jwt:
  secret: ${JWT_SECRET:VGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yUXVpekh1YkF1dGhTZXJ2aWNlMTIzNDU2Nzg5}

server:
  port: ${SERVER_PORT:9000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0

zipkin:
  tracing:
    endpoint: ${ZIPKIN_ENDPOINT:http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans}